title: veni, vidi
#description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://alexv.ro
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems:
  - jekyll-paginate
  - jemoji

paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
# - title: Biking
#   url: /biking

social:
  twitter: alex_vidrean
  instagram: alex_vidrean
  px500: alexvidrean
  github: vidi42

google_analytics:
